client_config_backend: file
client_config:
    client_id: 552299935049-qleq483hhdin6tsj1n9itd36deehq61p.apps.googleusercontent.com
    client_secret: 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

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
    - https://www.googleapis.com/auth/drive
    - https://www.googleapis.com/auth/drive.install